### ISSUE TITLE
Work plan

### ISSUE THREAD

**Issue by xin-huang** [xin-huang/sstar#20]
Hello @jalhackl 

Based on our discussion this afternoon, here is what we should do:

- [ ] Please create a new branch in this repo and you can upload you codes there. It is easier to do code review here.
- [ ] Please send me a sample data so that I can replicate the error you found in `stats.py`
- [ ] Our first goal is to faithfully replicate what `ArchIE` does and integrate their algorithm into `sstar`. You have several good ideas to improve the `ArchIE` algorithm, we can do this in the next project.
- [ ] We will test how the `ArchIE` algorithm performs on unphased data.
- [ ] We will also test how different sizes of balanced and imbalanced datasets affect the performance of the `ArchIE` algorithm.
- [ ] We will replace `ms` for `sstar` with `msprime`.
- [ ] We should also test how these methods perform in models without introgression.

cc @kuhlwilm
